### ISSUE TITLE
Make extension available via Packagist

### ISSUE THREAD

**Issue by markuspoerschke** [mittwald/typo3-web2pdf#100]
It is recommended to install PHP packages like TYPO3 extensions using Packagist. Therefore it would be benefitial to add this extension also to [packagist.org](https://packagist.org/).

This allows to install the extension using the command `composer require mittwald/web2pdf`.

**Comment by pstranghoener** [comment]
Its now available on packagist: https://packagist.org/packages/mittwald/web2pdf
