### ISSUE TITLE
pdfStyleSheet = print doesn't seem to work correctly

### ISSUE THREAD

**Issue by scoutie78** [mittwald/typo3-web2pdf#101]
Hi!
I've been trying to style my document for the last couple of days, but seem to have hit a major roadblock. Any help would be greatly appreciated.

My print-Stylesheet only shows one of the images from a page on the left side with the text arranged around it (exactly the way I want it). In the generated PDF however, all images are listed above the text and I can't alter or hide these images via CSS. The only way to remove the images from the PDF is to hide them in the Typo3 backend.

I'm using:
TYPO3 8.7.24
PHP 7.1
web2pdf 1.2.2

Kind regards,
Dani

**Comment by bihor** [comment]
I have a similar problem. When I set 
config.compressCss =1
then the generated PDF contains absolutly no styling (no CSS style works).
With
config.compressCss =0
I get only an empty page with no content at all...
I guess this is a problem of mPDF.

**Comment by pstranghoener** [comment]
Its a bug in mpdf which we are using, so we can not help with this bug.
