### ISSUE TITLE
Could not analyse class: "Mpdf\Mpdf"

### ISSUE THREAD

**Issue by cosmox** [mittwald/typo3-web2pdf#104]
Hi there,
after the update from 1.2.2 to version 1.2.3 i got this error now:
 
Could not analyse class: "Mpdf\Mpdf" maybe not loaded or no autoloader? Class Mpdf\Mpdf does not exist

Error still exists after deleting all Caches (FE/BE/OPCODE/AUTOLOAD)
Used TYPO3 Version: Typo3 8.7.24

Any hints?

**Comment by Aero91** [comment]
Same issue

**Comment by webdev2027** [comment]
Jep. Same here. No composer install, TYPO3 8.7.24 with PHP 7.2.
Extension worked with 1.2.2 perfectly.

**Comment by typo3-solution** [comment]
Install https://extensions.typo3.org/extension/mpdf/

**Comment by cosmox** [comment]
@typo3-solution thanks but maybe this is a workaround not realy a solution, because mpdf is a systemwide php lib, i have to install it once for all vHosts, this works with web2pdf v. 1.2.2 and earlier.
Now i have to install mpdf inside every TYPO3 Instanz (if i want to use the current version).
So if mpdf have a security bug...... it is not a simple update by the OS Packagemanager anymore :(
And if mpdf is a requirement of web2pdf .. it schould be resolved by the Extension manager or composer.

my2cent

**Comment by pstranghoener** [comment]
We  fixed in v1.2.4 and v2.0.0
