### ISSUE TITLE
Uncaught TYPO3 Exception: Not a TrueType font: version=168430090 | Mpdf\MpdfException thrown in file phar[...]

### ISSUE THREAD

**Issue by HansDump** [mittwald/typo3-web2pdf#106]
Hey,
a project is throwing this exeption all the time in web2pdf\Libraries\mpdf.phar\vendor\mpdf\mpdf\src\TTFontFile.php on line 271. 
If I am right, how can I add / remove my custom font? It's not documented. 
In this case it's a Google font.

Thank you!
Best regards.

web2pdf v1.2.2
typo3 v7.6.32

**Comment by pstranghoener** [comment]
Custom Fonts can be done with an overwrite for Resources/Public/Fonts
