### ISSUE TITLE
web2pdf erzeugt leere Seiten vor dem Content

### ISSUE THREAD

**Issue by izaquieltome** [mittwald/typo3-web2pdf#107]
Seit kurzem produziert web2pdf bei einem Projekt, welches ich betreue, "leere" Seiten vor dem eigentlichen Content. 
Die erste Seite trägt einen Titel, danach kommen 3 leere Seiten und eine mit einem nicht sichtbaren Link/Anker. 
Erst dann kommt der Content.
Aktiv wurde in dem bereich an dem Projekt nichts geändert, und ich kann den fehler bisher nicht ausmachen ...

PHP-Version 7.2.18, Typo3 Version 8.7.22 und web2pdf Version 1.2.3.

Auch dieser Fheler tritt ständig auf:
Core: Error handler (FE): PHP Warning: Division by zero in /var/www/vhosts/psz.co.at/httpdocs/typo3conf/ext/mpdf/Resources/Private/Libraries/vendor/mpdf/mpdf/src/Tag/Img.php line 377 
(Ohne die Extension "mpdf" zu laden erhalte ich den fehler Could not analyse class: "Mpdf\Mpdf" ( #104 ) 

https://www.psz.co.at/jobs/stellenbeschreibung.html?tx_stebiojobs_joblist%5Bjob%5D=30&tx_stebiojobs_joblist%5Baction%5D=show&tx_stebiojobs_joblist%5Bcontroller%5D=Job&cHash=1ed23f512b9f6238da4e2d0f23dc4364&tx_web2pdf_pi1%5Bargument%5D=printPage&tx_web2pdf_pi1%5Baction%5D=&tx_web2pdf_pi1%5Bcontroller%5D=Pdf

Ein Link zu einem dieser PDF's wäre dieser ... Vielleicht hat jemand einen Ansatz, was hier schief läuft.

Liebe Grüße,
Iza

**Comment by pstranghoener** [comment]
We fixed that in v1.2.4 and v2.0.0
