### ISSUE TITLE
Difference in Commit tagged with '1.1.6' composer.json and ext_emconf.php

### ISSUE THREAD

**Issue by fabianbruggmann** [mittwald/typo3-web2pdf#111]
In Version "1.1.6" there is a difference in the TYPO3 dependency.

### ext_emconf.php
https://github.com/mittwald/typo3-web2pdf/blob/9f5642c7199663101c688edf4eaf4e34f49829a1/ext_emconf.php#L40

### composer.json
https://github.com/mittwald/typo3-web2pdf/blob/9f5642c7199663101c688edf4eaf4e34f49829a1/composer.json#L11

Since versions "1.1.4" and "1.2.1" have TYPO3 "7.6.x" as a dependency I believe this to be an error, which could be detrimental when changing from non-composer-mode to composer-mode on old installations, when preparing an upgrade.

**Comment by pstranghoener** [comment]
Thats hard to fix in old versions. In the new version its correct, so we close that issue.
