### ISSUE TITLE
Wrong version display in extension list = fonts not working?

### ISSUE THREAD

**Issue by kriemhildt** [mittwald/typo3-web2pdf#126]
Hello there,

I installed the extension via composer in v. 2.0.1 for testing, but it always shows another version in my extension list in the BE:

![grafik](https://user-images.githubusercontent.com/88493491/153159126-5411ebab-07e2-44c3-8290-511df6f0ddc4.png)

![grafik](https://user-images.githubusercontent.com/88493491/153159172-9ad63bcd-20e0-4fee-96a9-f2eb267eef31.png)

Also I can't seem to change the font style of my PDF. Are these issues in any way connected? If not, why won't the font styles work and why is there a totally wrong version number in the BE?

**Comment by derhansen** [comment]
The wrong versions number is a result of a TER upload script where the incremental update of the version number in `ext_emconf.php` did not work properly. 

However, the wrong version number has most likely nothing to do with your problem that fonts are not working. There is an open issue #116, where some additional information on the topic is provided.

**Comment by kriemhildt** [comment]
Thank you for your answer. I will continue the font concerning topic in the other issue.
Regarding the version number: If that's no problem in the long run, will this still be fixed?

**Comment by derhansen** [comment]
The version number would be fixed, when/if an updated version of the v2 version of the extension will be uploaded.
