### ISSUE TITLE
Images not generated

### ISSUE THREAD

**Issue by MiladinBojic** [mittwald/typo3-web2pdf#127]
Hello, there are no images in generated pdfs and this is what I have:

TYPO3: 10.4.30
PHP: 7.2.34
web2pdf: 2.0.1

I have tried with simple image tag 
`<img src="fileadmin/path/to/file.jpg" />`

I have tried also with content type images and fluid_styled_content.

Both work in web, but there is no image in pdf. 
Actually, I got the icon for missing image, what we normally have in browser when we missing images.

Is there maybe some problem with paths?

Or what else could I check?

Also I found no issue in Install tool.

Best Regards,
Miladin.

**Comment by derhansen** [comment]
Please make sure to add a trailing slash to the image: `<img src="/fileadmin/path/to/file.jpg" />`. Ensure to clear the frontend cache after modifying the image path.

Tested successfully with version 3.0.0 of the extension

**Comment by MiladinBojic** [comment]
@derhansen thx. 
Actually, It was error of mine.
As I could see, the images are fetched using curl.
I work with docker and docker container had no access to localhost of host. 

So this was not the error of web2pdf.
