### ISSUE TITLE
Cannot find TTF TrueType font file "DejaVuSansMono.ttf" in configured font directories.

### ISSUE THREAD

**Issue by marcelbaklouti** [mittwald/typo3-web2pdf#129]
I use web2pdf 3.0.0 in Typo3 11.5. 
When I try to create a PDF I always get the error `Cannot find TTF TrueType font file "DejaVuSansMono.ttf" in configured font directories.`

This is the same Error as in the Issue [https://github.com/mittwald/typo3-web2pdf/issues/89].

**Comment by derhansen** [comment]
Fixed in version 3.0.1
