### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by kpurrmann** [mittwald/typo3-web2pdf#13]

**Comment by DavidBruchmann** [comment]
Example for pdfPregSearch and pdfPregReplace:
```
plugin.tx_web2pdf.settings {
	pdfPregSearch {
		1 = /^(.*)<!--TYPO3SEARCH_begin-->(.*)<!--TYPO3SEARCH_end-->(.*)$/s
	}
	pdfPregReplace {
		1 = $2
	}
}
```
Without these settings images never have been found (in TYPO3 6.2) but shown as red squares after these settings content is shown really nice and images are shown like on the website.

**Comment by DavidBruchmann** [comment]
If the website includes several areas wrapped with "|", then the expression above is not working and had to be adjusted individually.

**Comment by DavidBruchmann** [comment]
To refine several parts wrapped with `"<!--TYPO3SEARCH_begin-->|<!--TYPO3SEARCH_end-->"` this setting can be used (explanation as comments):
```
plugin.tx_web2pdf.settings {
	pdfPregSearch {
		# getting all content between the first "<!--TYPO3SEARCH_begin-->" and the last "<!--TYPO3SEARCH_end-->"
		1 = /^(.*)<!--TYPO3SEARCH_begin-->(.*)<!--TYPO3SEARCH_end-->(.*)$/s
		# filtering all between the search-parts
		2 = /<!--TYPO3SEARCH_end-->(.*?)?<!--TYPO3SEARCH_begin-->/s
	}
	pdfPregReplace {
		1 = $2
		2 = $1
	}
}
```

**Comment by pstranghoener** [comment]
Sorry for the delay could you make a PR for the documentation?

Thanks Philipp
