### ISSUE TITLE
Zero bytes files since upgrade to 11

### ISSUE THREAD

**Issue by ElectricMud** [mittwald/typo3-web2pdf#130]
Since the upgrade to TYPO3 11.5 I get PDF-files that are zero bytes. Am I missing something? Are there additional requirements?

**Comment by derhansen** [comment]
Basically this should work out-of-the-box. Did you notice, that the TypoScript files have been renamed (see https://github.com/mittwald/typo3-web2pdf/releases/tag/v3.0.0). If you included the TypoScript files of the extension like `<INCLUDE_TYPOSCRIPT: source="FILE:EXT:web2pdf/Configuration/TypoScript/setup.txt">`, you must change this to `<INCLUDE_TYPOSCRIPT: source="FILE:EXT:web2pdf/Configuration/TypoScript/setup.typoscript">` (both for constants and setup).

**Comment by derhansen** [comment]
Closing issue, since no feedback
