### ISSUE TITLE
Support needed after update to templavoila plus 8 

### ISSUE THREAD

**Issue by derBoogie** [mittwald/typo3-web2pdf#132]
I'm using templavoila plus (TVP) on one of my websites.
After the update to version 8 of TVP, I need some help to adjust my user_function to work with web2pf.

```
public function getChildTemplate(array $conf, &$pObj)
{
	$result = '';
	if (isset($conf['conf']['value']) && $conf['conf']['value'] = 'pdf')
	{
		$toRec = $pObj->markupObj->getTemplateRecord($conf['toRecord']['tx_templavoilaplus_to'], $conf['conf']['value'], $GLOBALS['TSFE']->sys_language_uid);
		if (is_array($toRec))
			$result = $conf['conf']['value'];
	}
	
	return $result;
}
```

Before the update of TVP  $conf['toRecord']['tx_templavoilaplus_to'] was the uid of the HTML template record.
Now TVP is organized in yaml config files and the database tables no longer exist.

My question is how to load the HTML template for the pdf generator?

**Comment by derhansen** [comment]
Since the issue is related to changes in templavoila plus, I suggest to ask for help either in TYPO3 Slack or GitHub Issues of the project (https://github.com/T3Voila/templavoilaplus)

**Comment by derBoogie** [comment]
@derhansen, thanks for the hint.
I posted my help request here: https://github.com/T3Voila/templavoilaplus/issues/485

**Comment by derBoogie** [comment]
I'm closing this issue, because the used function getChildTemplate is obsolete.
