### ISSUE TITLE
pdfPageOrientation setting is ignored after typo3 11 update

### ISSUE THREAD

**Issue by AnnikaSchuster** [mittwald/typo3-web2pdf#133]
after version update from 2.0.1 to 3.0.1, the pdfPageOrientation setting is ignored, the pdfs always rendered in landscape orientation, but i need the portrait orientation

**Comment by derhansen** [comment]
Please check the breaking changes related to version 3.0.0 - see https://github.com/mittwald/typo3-web2pdf/releases/tag/v3.0.0

You must ensure to reference to the new `constants.typoscript` and `setup.typoscript` in your sitepackage, if you included the extensions TypoScript using `@import` or `<INCLUDE_TYPOSCRIPT: source="">`. If the TypoScript settings are missing, `plugin.tx_web2pdf.settings.pdfPageOrientation` defaults to `L` (landscape) which might explain, why your settings are ignored.

**Comment by AnnikaSchuster** [comment]
Thank you for your help, the constants.typoscript and setup.typoscript are included in my extension, the setting `plugin.tx_web2pdf.settings.pdfPageOrientation` is set to `P` but the problem still exist
