### ISSUE TITLE
Content-Disposition inline or attachment

### ISSUE THREAD

**Issue by klodeckl** [mittwald/typo3-web2pdf#15]
Sometimes the PDF should be displayed inline in the browser window instead of making a download. For that Classes/View/PdfView.php line 104 should be changed from
header('Content-Disposition: attachment; filename="' . $this->fileNameUtility->convert($pageTitle) . '.pdf' . '"');
to
header('Content-Disposition: inline; filename="' . $this->fileNameUtility->convert($pageTitle) . '.pdf' . '"‘);
stehen.

A typoscript option for that would be great!

**Comment by martin-helmich** [comment]
This should be a TypoScript option, defaulting to `Content-Disposition: attachment`; anything else would break backwards compatibility.

**Comment by christian-hellmuth** [comment]
+1 for that TypoScript option as it will also make it easier to debug the generated PDF output when not set to attachment.

**Comment by kpurrmann** [comment]
#38
