### ISSUE TITLE
Uncaught TYPO3 Exception: String needed as argument 

### ISSUE THREAD

**Issue by digitalgenossen** [mittwald/typo3-web2pdf#20]
Wir haben zwei Hosting-Accounts bei Mittwald (ein Hosting-Paket + Managed Server), in denen eine identische TYPO3 (6.2) Installation liegt. Wir haben einen passwortgeschützten Bereich, in den man sich einloggen soll / muss (fe user). Darin befinden sich dann Seiten, aus denen wir ein PDF erzeugen möchten. Die Seiten müssen zugriffsgeschützt sein.

Wir haben in beiden Accounts die letzte Version von web2pdf laufen. Im Hosting-Paket funktioniert das Erzeugen der PDF-Datei augenscheinlich wie gewünscht. Auf dem Managed Server kommt es zu einer Fehlermeldung, wenn ich auf den Drucken-Link klicke:

![error](https://cloud.githubusercontent.com/assets/6715837/9443705/e0fc4204-4a82-11e5-9ec8-479376b8d633.jpg)

Was debeutet dieser Fehler. Ist das ein Bug in der extension oder haben Sie einen Tipp, welche Einstellungen zu diesem Fehler führen könnten?

Vielen Dank

**Comment by pstranghoener** [comment]
Could you take a look at it @kpurrmann ?

**Comment by kpurrmann** [comment]
@pstranghoener i will fix it until end of week

**Comment by pstranghoener** [comment]
We uploaded the new version 1.1.1 to the TER.
