### ISSUE TITLE
pdfStyleSheet "print" does not work

### ISSUE THREAD

**Issue by derpepe** [mittwald/typo3-web2pdf#25]
Hi there,

I use the following configuration, created by the constants editor:
```
plugin.tx_web2pdf.settings.pdfStyleSheet = print
```

The print-Stylesheet hides the navigation, but the navigation is present in the PDF. It is not present if I print the page, so the Print-CSS is working correctly.

The generation of the PDF works, so Web2PDF should be installed correctly.

Is this a bug in Web2PDF? Does anyone else have this issue?

Peter

**Comment by derpepe** [comment]
I just came over #6 which is kind of related.

I use TYPO3 6.2.14.

The following CSS-Files are included in the webpage:
```
<link rel="stylesheet" type="text/css" href="/typo3conf/ext/xxx/Resources/Public/styles/main.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/typo3conf/ext/xxx/Resources/Public/styles/print.css" media="print" />
```

**Comment by zitschmedia** [comment]
Hi Peter,
same issue here with TYPO3 6.2.1.5. I tryed all versions but no solution up to now.
Did you find any workaround?

**Comment by derpepe** [comment]
Hi,
not yet. I guess we'll have to investigate.. :-/

**Comment by zitschmedia** [comment]
Hi Peter 
in my case it helped to disable compression of the print.css:
printlayout.disableCompression = 1

**Comment by derhansen** [comment]
Any news on this issue? I have the same problem. Installed extension on a very basic TYPO3 installation, added a custom CSS file for "print", but CSS styles seems to be ignored completely. 

Any suggestions?

**Comment by kpurrmann** [comment]
I could find out, that the mpdf library has problems to load multiple css resources.

For example if you use an main.css and an additional print css to set your print layout mpdf only uses the print css and ignores the main.css.

One workaround could be to copy your main.css to print.css plus your additional styles. I know that this is not a good way but solved the problem.

But I will have a look at it and find a better solution.

**Comment by kpurrmann** [comment]
Figured out that this weird behaviour is caused by mPdf attribute CSSselectMedia. 
Instead of setting it to "all" I have to unset this attribute. 

Now it seems that css is handled the correct way. If you change the settings to "print" or "screen" only these stylesheets are used. 

Started pull request.

**Comment by st4lker104** [comment]
this fix works just fine! Thanks a lot :)
