### ISSUE TITLE
web2pdf URLs are indexed by indexed_search

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/typo3-web2pdf#28]
Original bug report by @kurtkk in #7:

> Hallo Herr Stranghöner, Hallo Herr Purrmann,
> 
> ich habe web2pdf eingesetzt und auch indexed_search bei st-josef-calw.de
> z.B.
> 
> Wenn ich nach einen Begriff suche und einen Treffer lande, dann passiert
> es häufig, dass der Link in der Gefunden-Liste auf das PDF der Seite zeigt!?
> (Beispiel: Suche nach "kupix" auf o.a. Seite und Sie werden zwei Treffer
> haben: a) im Impressum und b) in einer News wobei b) eine besagte PDF ist)
> 
> Ich habe in der HTML-Vorlage schon mal in der Suchform von "post" auf
> "get" geändert aber das kann es ja nicht sein. Es kann, wie mir gerade
> einfällt ja auch nicht an web2pdf liegen, es muss ja in der Indizierung
> liegen, da die Links so aussehen:
> 
> http://st-josef-calw.de/index.php?id=45&tx_news_pi1[day]=1&tx_news_pi1[month]=8&tx_news_pi1[news]=3&tx_news_pi1[year]=2015*&tx_web2pdf_pi1[action]=&tx_web2pdf_pi1[argument]=printPage&tx_web2pdf_pi1[controller]=Pdf&cHash=25594bd64db52934e968d06ecab07c3c*
> 
> Haben Sie eine Idee, wie die Parameter "_tx_web2pdf_pi1_" in den Link
> kommen?
> 
> Mit einem freundlichen Gruß aus Jülich
> 
> Kurt Kunig

**Comment by martin-helmich** [comment]
@pstranghoener FYI

**Comment by pstranghoener** [comment]
Fixed in new version 1.2.0 of web2pdf
