### ISSUE TITLE
Not possible to set pdfPregSearch etc.

### ISSUE THREAD

**Issue by MoppieMop** [mittwald/typo3-web2pdf#32]
In ModuleOption.php Function initializeObject there is a check for ```$this->options['pdfPregSearch']``` but this does not work. You have to check for ```$this->options['pdfPregSearch.']``` (a dot at the end of the key!).
Otherwise you are not able to set pdfPregSearch or pdfStrSearch.

I use TYPO3 6.2.15.

**Comment by martin-helmich** [comment]
Fixed in #33. Thanks for reporting this issue!
