### ISSUE TITLE
Page format change does not work

### ISSUE THREAD

**Issue by klodeckl** [mittwald/typo3-web2pdf#48]
If I define A5 or A3 as page format, it is still rendered as A4. But when I change the orientation to L, the format is applied (but I need A5 in portrait mode). Even if I hardcode A5 in Classes/View/PdfView.php, it is still A4.

**Comment by kpurrmann** [comment]
Will have a look at it later on. May you try to set page format manually:

`$pdf->_setPageSize($pageFormat, $pageOrientation);` in line 164

**Comment by klodeckl** [comment]
Thanks, that worked!

**Comment by martin-helmich** [comment]
Should have already been fixed with #49.
