### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by fnagel** [mittwald/typo3-web2pdf#50]
It seems the current implementation comes without any caching. That what it seems looking at the uncached action and the deletion of the PDF after pushing it to the user. 

Is that assumption correct? If so, are there any plans to implement some caching into this extension?

**Comment by kpurrmann** [comment]
Currently there are no efforts to implement some caching functionality. Will keep that issue. Maybe we are going to implement it later on. Feel free to contribute some code or some suggestions on this issue.

**Comment by fnagel** [comment]
I've ended up using a custom solution .

Not sure how to achieve proper caching using TYPO3 page cache (if thats even possible) but I've added some basic caching based on caching a once generated file and clearing it by timestamp and clear cache hook. Something similar should be easily possible to this extension.

**Comment by pstranghoener** [comment]
You didnt make a PR so i will close the issue.
