### ISSUE TITLE
Margin change does not work

### ISSUE THREAD

**Issue by Gloumi** [mittwald/typo3-web2pdf#51]
Hi, I tried to change pdf margins to 0 but this doesn't work : 
- If I set pdfLeftMargin and pdfRightMargin to any value there is no changes in my PDF
- For pdfTopMargin it doesn't works with 0 but works with other values, I think the php condition below consider that 0 is null and set it to 15

`$topMargin = ($this->options->getPdfTopMargin()) ? $this->options->getPdfTopMargin() : '15';`

Another question : Why there is no pdfBottomMargin property ?

**Comment by meierz** [comment]
Same here.
Even changing these lines does not have any effect:
```
$leftMargin = ($this->options->getPdfLeftMargin()) ? $this->options->getPdfLeftMargin() : '40';
$rightMargin = ($this->options->getPdfRightMargin()) ? $this->options->getPdfRightMargin() : '40';
$topMargin = ($this->options->getPdfTopMargin()) ? $this->options->getPdfTopMargin() : '40';
```
