### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by papillon6** [mittwald/typo3-web2pdf#53]
Hi Mittwald-Team,

the "print currrent page" link leads to an error 500. Server-log says:

> error parsing headers: duplicate header 'Content-Type'

TYPO3 7.6.4, web2pdf 1.1.4, PHP 5.6.12 (FastCGI)
Is this a known 'bug'?

Regards!

**Comment by lisardo2** [comment]
It is a problem for all who uses FastCGI. Apparently the extension is sending twice the response to the browser. So currently the extension seems not to work in fastcgi.

**Comment by topfender** [comment]
Will / can this be fixed or no chance?

**Comment by stephangrass** [comment]
Will / can this be fixed or no chance????
