### ISSUE TITLE
Altering Header/Footer Partial 

### ISSUE THREAD

**Issue by izzycole** [mittwald/typo3-web2pdf#54]
Hi!

Is there any way to alter Header and Footer Partials depending on PAGENO? 

It would be nice to have Logo / Address etc. only on first page. Adding class="page{ocb}PAGENO{ccb}" e.g. does not work since the replacement of {PAGENO} seems to happen after CSS-rendering in mdpf.php.

Maybe this issue is related: https://github.com/mittwald/typo3-web2pdf/issues/14

**Comment by kpurrmann** [comment]
See #14
