### ISSUE TITLE
No installation from TER possible in T3 v. 6.2.21

### ISSUE THREAD

**Issue by pixelink** [mittwald/typo3-web2pdf#55]
Hi, i tried to install the extension v1.1.4 from TER (in different 6.2.21 instances) but it fails. I get the wheel of death and the ext appears in installed list but claims that mpdf is needed.

Even downloading it via zip and installing it doesn't work. 
Installation from TER with T3 7.6.x works like a charm.

Any ideas?

**Comment by briezler** [comment]
Remove composer.json and composer.lock when using from TER and TYPO3 6.2

**Comment by pstranghoener** [comment]
Will be fixed in next Version for TER

**Comment by chricken** [comment]
Great, when is the 1.1.5 expected to be released?

**Comment by pstranghoener** [comment]
Sorry, for the delay. We will release the version today.

**Comment by pstranghoener** [comment]
We just upload the version 1.1.5 to the TER. It must be available in 15 minutes. https://typo3.org/extensions/repository/view/web2pdf 

Best Regards Philipp
