### ISSUE TITLE
Plugin doesn't respect own templateRootPath

### ISSUE THREAD

**Issue by r4fx** [mittwald/typo3-web2pdf#56]
Overriding `layoutRootPath` works fine, but `templateRootPath` doesn't, 

my code looks like:

``` js
plugin.tx_web2pdf {
    view {
        templateRootPath = fileadmin/assets/plugins/web2pdf/Templates/
        partialRootPath = fileadmin/assets/plugins/web2pdf/Partials/
        layoutRootPath = fileadmin/assets/plugins/web2pdf/Layouts/
    }
}
```

TYPO3 7.6.5

**Comment by webdev2027** [comment]
Hi, this is working for me. Try it like this ...

`plugin.tx_web2pdf {
	view {
		templateRootPaths.100 = fileadmin/assets/plugins/web2pdf/Templates/
	}
}`

Be sure, that your Template folder also include the folder `pdf`, like ..
![bildschirmfoto 2016-08-22 um 16 10 01](https://cloud.githubusercontent.com/assets/5501876/17857565/88d41af6-6882-11e6-83b0-19f72a5afcb8.png)

**Comment by plojewski** [comment]
Nope, it doesn't work at all. In constants:

plugin.tx_web2pdf {
	view {
		templateRootPath = files/assets/plugins/web2pdf/Templates/
	}
}

in Setup:

plugin.tx_web2pdf {
    view {
        templateRootPath.100 = files/assets/plugins/web2pdf/Templates/
    }
}

or

plugin.tx_web2pdf {
    view {
        templateRootPath= files/assets/plugins/web2pdf/Templates/
    }
}

I've got GeneratePdfLink.html file in Pdf folder.

**Comment by xraysoft** [comment]
Has anyone found a solution? Whether I follow the instructions in the documentation or the proposal you have made here, it does not work.

**Comment by plojewski** [comment]
You have to make pdf link by yourself in TS (if you don't want to change ext sources):
`
        lib.pdfLink = TEXT
        lib.pdfLink {
           value = Download this page as PDF
            typolink.parameter.data = TSFE:id
            typolink.additionalParams = &tx_web2pdf_pi1[argument]=printPage&tx_web2pdf_pi1[action]=&tx_web2pdf_pi1[controller]=Pdf
            typolink.target = _blank
            stdWrap.noTrimWrap = |<span class="icon icon-file-outline icon--lg"></span> <span>|</span>|
        }
`

**Comment by xraysoft** [comment]
Thanks, good solution. This works!

**Comment by Kephson** [comment]
It works in TYPO3 7.6.x with this setup:
`plugin.tx_web2pdf {
    view {
        templateRootPaths.100 = mypath/Web2pdf/Templates/
        partialRootPaths.100 = mypath/Web2pdf/Partials/
        layoutRootPaths.100 = mypath/Web2pdf/Layouts/
    }
}`

But please update the TypoScript in the extension with the templateRootPaths, partialRootPaths and layoutRootPaths.
