### ISSUE TITLE
Bugs & Feedback

### ISSUE THREAD

**Issue by Scopestyle** [mittwald/typo3-web2pdf#57]
Hi @martin-helmich, I have a few questions / issues

**Unable to set custom path**
- Could it be that the path to the template is hardcoded somewhere? I changed the path in the constants, but the plugin keeps grabbing the original file for some reason. Other settings like pdfDestination work just fine (I tried to change the paths in setup, constants and constants editor in the TYPO3 interface) I ended up changing the original file, which is less then ideal.

**Translation -Fixed-**
- Is it possible to overwrite the name using TypoScript for multilanguage purposes? I noticed there is no web2pdf folder being added to the l10n/de/ folder. Not sure if that makes a difference or not. 
  I tried the following logic but it doesn't work:

```
plugin.web2pdf {
        _LOCAL_LANG {
            de.web2pdf.printLabel = PDF Herunterladen
            en.web2pdf.printLabel = Download PDF
    }
}
```

**Unable to render styles with compression on**
- I noticed that when the CSS is compressed `compressCss = 1` `concatenateCss = 1,` the PDF creator cannot read any styles. I assume this is a bug. The workaround is setting the plugin to `pdfStyleSheet = pdf` (yes, that works) and excluding the print css from compression. Then creating a new CSS with `media = pdf`in typoscript.

**Unable to render SVG images**
- Another bug in rendering, SVG images (increasingly common on the web) are rendered as black squares.(I realize this is a limitation of the mpdf tool, not so much web2pdf)

**Custom path to mpdf**
- It would be nice if there could be a custom location of the mpdf module. I changed some settings to add custom font rendering. When I would update the web2pdf plugin these changes are gone.

Kind regards,

Erik

**Comment by Scopestyle** [comment]
Well the language issue I firgured out, needs to be `tx_web2pdf.` The question on the templates still stands.

**Comment by eurokdj** [comment]
I have exactly the same problem : I can't display anthing else than this aweful "Print Current Page" link, instead of the clean icon link that I prepared in a html file that I uploaded in /fileadmin/files/

I am on Typo 7.6.9 under Windows (Wamp) with pre-configured installation (the official Introduction package)

Is this really like this that I have to insert it inside the Constants field of my Template

`plugin.tx_web2pdf.view= fileadmin/files/generatepdflink.html`

I also tried, just like Scopestyle did,

```
plugin.tx_web2pdf{
        _LOCAL_LANG {
            fr.web2pdf.printLabel = Version PDF
            en.web2pdf.printLabel = Download PDF
    }
}
```

No success either (maybe because there is no web2pdf/ folder inside /l10n/fr)

I think I have no other way but modifying the content of typo3conf\ext\web2pdf\Resources\Private\Templates\Pdf\GeneratePdfLink.html, even if I don't think this is good practice...

**Comment by Scopestyle** [comment]
Hey @eurokdj did you include the config as well? I added the following code in my setup TS and it works for me in 7.6.9:

```
plugin.tx_web2pdf {
    view {
        templateRootPath = {$plugin.tx_web2pdf.view.templateRootPath}
        partialRootPath = {$plugin.tx_web2pdf.view.partialRootPath}
        layoutRootPath = {$plugin.tx_web2pdf.view.layoutRootPath}
    }

    settings {
        pdfPageFormat = {$plugin.tx_web2pdf.settings.pdfPageFormat}
        pdfPageOrientation = {$plugin.tx_web2pdf.settings.pdfPageOrientation}
        pdfLeftMargin = {$plugin.tx_web2pdf.settings.pdfLeftMargin}
        pdfRightMargin = {$plugin.tx_web2pdf.settings.pdfRightMargin}
        pdfTopMargin = {$plugin.tx_web2pdf.settings.pdfTopMargin}
        pdfStyleSheet = {$plugin.tx_web2pdf.settings.pdfStyleSheet}
        pdfDestination = {$plugin.tx_web2pdf.settings.pdfDestination}
        useCustomHeader = {$plugin.tx_web2pdf.settings.useCustomHeader}
        useCustomFooter = {$plugin.tx_web2pdf.settings.useCustomFooter}

        pdfPregSearch {
            1 =
        }

        pdfPregReplace {
            1 =
        }

        pdfStrSearch {
            1 =
        }

        pdfStrReplace {
            1 =
        }
    }
}

lib.web2pdf = USER
lib.web2pdf {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    pluginName = Pi1
    extensionName = Web2pdf
    vendorName = Mittwald
    controller = Pdf
    action = generatePdfLink
}

plugin.tx_web2pdf {
        _LOCAL_LANG {
            de.web2pdf.printLabel = Datenblatt Herunterladen
            en.web2pdf.printLabel = Download Technical Info
    }
}
```

**Comment by eurokdj** [comment]
Thank you for your quick reply. At first, I tried exactly the solution you suggested (apart from the <f:cObject typoscriptObjectPath="lib.web2pdf" />  line because I did not know exactly where to insert it, I am still quite a beginner...
With a little adaptation however, since default langage is French :

```
plugin.tx_web2pdf {
        _LOCAL_LANG {
          default.web2pdf.printLabel = Version PDF            
          en.web2pdf.printLabel = Download Technical Info
    }
}
```

And it worked ! in spite of the fact that, as I mentioned before, there is no web2pdf/ folder inside /l10n/fr

Afterwards, since I really wanted to have an icon instead (even if it would have been possible with CSS too), I made it evolve :

```
plugin.tx_web2pdf {
        _LOCAL_LANG {
          default.web2pdf.printLabel = <i class="glyphicon glyphicon-save-file"></i>            
          en.web2pdf.printLabel = Download Technical Info
    }
}
```

And finally I wondered why I should keep all the code part 

```
plugin.tx_web2pdf {
    view {
        templateRootPath = {$plugin.tx_web2pdf.view.templateRootPath}
        partialRootPath = {$plugin.tx_web2pdf.view.partialRootPath}
        layoutRootPath = {$plugin.tx_web2pdf.view.layoutRootPath}
    }

    settings {
(...)
    controller = Pdf
    action = generatePdfLink
}
```

since it is already inside the extension.

So I took the risk to removing, and my icon is still there :-)

**Comment by Scopestyle** [comment]
No risk there as you said, the plugin itself also includes the code. Glad you got it figured out!

**Comment by pstranghoener** [comment]
Could this issue be closed?

**Comment by r4fx** [comment]
I don't think so, i still have problem with `pdf StyleSheet`.
My print stylesheets are ignored.

**Comment by pstranghoener** [comment]
@r4fx Please make a new issue if it is not working with with new version 1.2.0 of web2pdf. Thnaks

**Comment by eurokdj** [comment]
Hello,

Thank you for the code ! Sorry but I completely stopped using Typo3, and
the project in which I used the plugin has been abandoned. Therefore I
can't test for the moment.

2016-07-13 12:35 GMT+02:00 Scopestyle <notifications@github.com>:

> Hey @eurokdj <https://github.com/eurokdj> did you include the config as
> well? I added the following code in my setup TS and it works for me in
> 7.6.9:
>
> plugin.tx_web2pdf {
>     view {
>         templateRootPath = {$plugin.tx_web2pdf.view.templateRootPath}
>         partialRootPath = {$plugin.tx_web2pdf.view.partialRootPath}
>         layoutRootPath = {$plugin.tx_web2pdf.view.layoutRootPath}
>     }
>
>     settings {
>         pdfPageFormat = {$plugin.tx_web2pdf.settings.pdfPageFormat}
>         pdfPageOrientation = {$plugin.tx_web2pdf.settings.pdfPageOrientation}
>         pdfLeftMargin = {$plugin.tx_web2pdf.settings.pdfLeftMargin}
>         pdfRightMargin = {$plugin.tx_web2pdf.settings.pdfRightMargin}
>         pdfTopMargin = {$plugin.tx_web2pdf.settings.pdfTopMargin}
>         pdfStyleSheet = {$plugin.tx_web2pdf.settings.pdfStyleSheet}
>         pdfDestination = {$plugin.tx_web2pdf.settings.pdfDestination}
>         useCustomHeader = {$plugin.tx_web2pdf.settings.useCustomHeader}
>         useCustomFooter = {$plugin.tx_web2pdf.settings.useCustomFooter}
>
>         pdfPregSearch {
>             1 =
>         }
>
>         pdfPregReplace {
>             1 =
>         }
>
>         pdfStrSearch {
>             1 =
>         }
>
>         pdfStrReplace {
>             1 =
>         }
>     }
> }
>
> lib.web2pdf = USER
> lib.web2pdf {
>     userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
>     pluginName = Pi1
>     extensionName = Web2pdf
>     vendorName = Mittwald
>     controller = Pdf
>     action = generatePdfLink
> }
>
> plugin.tx_web2pdf {
>         _LOCAL_LANG {
>             de.web2pdf.printLabel = Datenblatt Herunterladen
>             en.web2pdf.printLabel = Download Technical Info
>     }
> }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mittwald/typo3-web2pdf/issues/57#issuecomment-232319059>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMCrl7zk33mMxZopAw_uwjrOmzmm7kq8ks5qVL-AgaJpZM4IyzIj>
> .
>



-- 
Karine SANCHE
Concepteur développeur PHP Java Android
Webmaster - Webdesigner - SEO
http://www.kdj-webdesign.com
