### ISSUE TITLE
Empty Page with fluid_styled_content

### ISSUE THREAD

**Issue by Pavitro** [mittwald/typo3-web2pdf#58]
Using fluid_styled_content with TYPO3 7.6.x I get only an empty PDF file.

**Comment by Pavitro** [comment]
Hi Scopestyle, you're right. Thanks a lot!

**Comment by webdev2027** [comment]
Hi everyone, I've the same problem. Install the extension, include static template, insert as a plugin .. I've got always an empty pdf. (TYPO3 7.6.10, fluid_styled_content, PHP 5.6.)

The other bugs & feedback from Scopestyle doesn't help me at all. I can write an own template, translate the locallang, ...  no problem.

I try the extension with the TYPO3 Introduction package and it works 'out of the box'.

I think my problem must sth. to to with my server?! What's wrong? No error, only an empty PDF.

**Comment by gg-philipp-duell** [comment]
Also creates an empty pdf when html output is reduced to one line.
e.g. when using the extension "sourceopt" 
Maybe sourceopt does not work exactly when reducing the html. But for anybody who faces the problem of an empty pdf this could be a hint.
web2pdf works fine, if html-output is not reduced.

**Comment by webdev2027** [comment]
Hi Philipp, I don't use Ext.sourceopt or Ext.min
Ghostscript is installed. Now I've got an other error:
`WriteHTML() requires $html be an integer, float, string, boolean or an object with the __toString() magic method. ` at `typo3conf/ext/web2pdf/Vendor/mpdf/mpdf/mpdf.php in line 15884.`  I've updated the extension to 1.1.6 (TYPO3 7.6, PHP5.6, GraphicsMagick) ?!?

**Comment by kpurrmann** [comment]
Should be fixed with #66.
