### ISSUE TITLE
Japanese Language

### ISSUE THREAD

**Issue by mwegmannnext** [mittwald/typo3-web2pdf#59]
Hi. We have the problem to generate output in japanese language. Only a sort of placeholder is the output. Is there a solution?

**Comment by pstranghoener** [comment]
Could be possible that mpdf fonts doesn't support japanese language.

**Comment by mwegmannnext** [comment]
Keine Möglichkeit, das Ding für japanisch und chinesisch zum laufen zu bringen? Kenne mich mit der Zeichensatz-Thematik zu wenig aus und weiss daher nicht ob es konfigurierbar wäre oder schlicht nicht möglich.

**Comment by pstranghoener** [comment]
Wenn Sie eine Schriftart finden die japanisch und chinesisch unterstützt und diese dann in mpdf einbinden. Sollte das ganze dann klappen. Hier die unterstützen Sprachen von mPDF https://mpdf.github.io/fonts-languages/fonts-language-cover-v5-x.html
