### ISSUE TITLE
How to work with this setting: plugin.tx_web2pdf.settings.pdfStyleSheet = print

### ISSUE THREAD

**Issue by kurtkk** [mittwald/typo3-web2pdf#6]
What does it mean?

in Typoscript an own includeCSS with media = print!?
page.includeCSS {
   file2 = ... pdf.css
   file2.media = print
}

OR / AND

in the main.css file a part like this:
@media print { #mm  { display:none; } }

Both don't work!?

**Comment by kpurrmann** [comment]
Following setup should work:
```
page.includeCSS.test = test.css
page.includeCSS.test.media = print
```
test.css:
``` 
#mm {display:none;}
```

With TypoScript option: `plugin.web2pdf.settings.pdfStyleSheet` you can change media of chosen stylesheet to `screen` or `all`. Default one is `print`.

**Comment by kurtkk** [comment]
So it only works if you have enclosed the css-items with
@media print { … }

without @media print { … } you have to rename the css-file to print.css!

**Comment by kurtkk** [comment]
Sorry, I wouldn't close this issue! ;-)

**Comment by kpurrmann** [comment]
It seems that the @media instruction in external files is ignored by mPDF library.
Therefore you should use an own external stylesheet for printing.
Like I wrote before, you should include it media type "print".  In this file there is no need for the @media statement.

**Comment by topfender** [comment]
I tried it like this:
TS:
page {
         includeCSS {
		print =[...]/Resources/Public/Styles/print.css
		print.media = print
	}
}
plugin.web2pdf.settings.pdfStyleSheet = print

print.css:
* {color:red;}
.header {display:none;}
a {text-decoration: none;}

But my PDF ignores all styles. What am I doing wrong?

**Comment by kpurrmann** [comment]
@topfender Did you include the static template?

**Comment by topfender** [comment]
yes
![web2pdf](https://cloud.githubusercontent.com/assets/13070580/9598398/732d2734-508b-11e5-89e6-34f0a0abaff5.JPG)

**Comment by kpurrmann** [comment]
Which TYPO3 Version do you use?

**Comment by topfender** [comment]
6.2.14
