### ISSUE TITLE
Runtime Deprecation Notice for mPDF

### ISSUE THREAD

**Issue by SvenJuergens** [mittwald/typo3-web2pdf#61]
hi,

i got a Runtime Deprecation Notice for mPDF. In the current version of mPDF it's already fix, so is it possible to update the source of mPDF?

`#1: PHP Runtime Deprecation Notice: Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor in .../web2pdf/Vendor/mpdf/mpdf/mpdf.php line 89`

**Comment by pstranghoener** [comment]
We updated mpdf library in version 1.1.6
