### ISSUE TITLE
Error with Frontend Editing

### ISSUE THREAD

**Issue by Batman777** [mittwald/typo3-web2pdf#62]
Hi,

when trying to activate the extension "feedit" I get the following error.
"The package "web2pdf" depends on "mpdf/mpdf" which is not present in the system."

Thank you

**Comment by Batman777** [comment]
Problem solved with deleting/renaming composer.json + composer.lock in folder "web2pdf"

**Comment by pstranghoener** [comment]
composer.json + composer.lock has been removed in version 1.1.5 already
