### ISSUE TITLE
Does not work with tx_news - ignores parameter

### ISSUE THREAD

**Issue by gg-philipp-duell** [mittwald/typo3-web2pdf#69]
Usign Web2Pdf to print News from tx_news as PDF does not work properly.
Web2Pdf ignores the tx_news parameters and always prints the first news that is shown on a news-detail-page wether another news is shown currently or not.

E.g. the url of a news currently shown would be:
**index.php?id=454**&no_cache=1&tx_news_pi1%5Bnews%5D=709&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Baction%5D=detail&cHash=bebd70f5b440c4b835684ff68f6a4711

Web2Pdf will generate a URL to download the pdf without the single-news-id:
**index.php?id=454**&no_cache=1&tx_web2pdf_pi1%5Bargument%5D=printPage&tx_web2pdf_pi1%5Baction%5D=&tx_web2pdf_pi1%5Bcontroller%5D=Pdf&cHash=1005da9f4ac26995f4c4ce69c7900b58

Where can i force web2pdf to use all parameters?

**Comment by gg-philipp-duell** [comment]
Seems to be a problem when using cooluri.

TYPO3 7.6.12
web2pdf 1.1.5
cooluri 1.1.3

**Comment by gg-philipp-duell** [comment]
Okay - Using:
`  <uriparts>
<part>
      <parameter>tx_news_pi1[news]</parameter>
      <lookindb>
      <to>SELECT path_segment,title FROM tx_news_domain_model_news WHERE uid=$1 AND sys_language_uid >= 0</to>
      <urlize>1</urlize>
      </lookindb>
    </part>
</uriparts>`
in the CoolUriConf.xml will prohibit web2pdf from generating the correct link to the pdf.
As soon as this rewriting is removed the pdf of any single news-item works.
But - the URLs get nasty.

Any ideas on that?

**Comment by r4fx** [comment]
In `/Templates/Pdf/GeneratePdfLink.html` to `f:link.action` add one additional attribute : `addQueryStringMethod="GET" `. This will keep query string from news detail.

And then in CoolUri configuration `CoolUriConf.xml` add

to `<uriparts>`

```xml
<part>
   <parameter>tx_web2pdf_pi1[argument]</parameter>
   <t3conv>1</t3conv>
</part>
```
to `<predefinedparts>`

```xml
<part>
    <parameter>tx_web2pdf_pi1[controller]</parameter>
</part>

<part>
    <parameter>tx_web2pdf_pi1[action]</parameter>
</part>
```

**Comment by gg-philipp-duell** [comment]
Great! That works!
Thanks a lot.

**Comment by gg-philipp-duell** [comment]
Great. That works!
Thanks a lot.
