### ISSUE TITLE
better to handle the ext. with the possibility to create an own fluid-template

### ISSUE THREAD

**Issue by kurtkk** [mittwald/typo3-web2pdf#7]
So the admin has the possibility to insert PDF-content like this:

// Quellenangabe
pdf_generator {
	10 = TEXT
	10 {
		data = date : U
      strftime = %d. %b. %Y
		wrap = <strong>PDF&nbsp;erstellt&nbsp;am&nbsp;|</strong><br />
	}
}

pdf_generator.15 = TEXT
pdf_generator.15.data = getenv:HTTP_REFERER
pdf_generator.15.wrap = <span class="pdf-quelle">Quelle: <strong>|</strong></span><br />

// Seitenname
pdf_generator.20 = TEXT
pdf_generator.20.data = page:title
#pdf_generator.20.if.isTrue.data = page:title
pdf_generator.20.required = 1
pdf_generator.20.wrap = Seitentitel: <strong>|</strong><br />

// Untertitel der Seite
pdf_generator.30 = TEXT
pdf_generator.30.data = page:subtitle
pdf_generator.30.if.isTrue.data = page:subtitle
pdf_generator.30.stdWrap.crop = 145 | ... | 1
pdf_generator.30.wrap = <em>&quot;|&quot;</em><br />

// Autor ausgeben
pdf_generator.40 = TEXT
pdf_generator.40.data = page:author
pdf_generator.40.if.isTrue.data = page:author
pdf_generator.40.wrap = | <br />

// Änderungsdatum
pdf_generator.50 = TEXT
pdf_generator.50 {
   field = SYS_LASTCHANGED
   stdWrap.strftime = %d. %b. %Y
   stdWrap.wrap = letzte Änderung am:&nbsp;| <br />
}

![pdf-header-beispiel_2015-08-03_120801](https://cloud.githubusercontent.com/assets/8299389/9035519/d7a48546-39d8-11e5-8303-08e1835e3e8f.png)

**Comment by pstranghoener** [comment]
We uploaded a new Version to the TER with the following Features:

• Configurable headers and footers for PDF pages
• Configurable page title
• Option to add page numbers to generated PDF pages

**Comment by kurtkk** [comment]
Great! - I'll test these new settings in the next hours!   :+1:

**Comment by kurtkk** [comment]
Hallo Herr Stranghöner, Hallo Herr Purrmann,

ich habe web2pdf eingesetzt und auch indexed_search bei st-josef-calw.de 
z.B.

Wenn ich nach einen Begriff suche und einen Treffer lande, dann passiert 
es häufig, dass der Link in der Gefunden-Liste auf das PDF der Seite zeigt!?
(Beispiel: Suche nach "kupix" auf o.a. Seite und Sie werden zwei Treffer 
haben: a) im Impressum und b) in einer News wobei b) eine besagte PDF ist)

Ich habe in der HTML-Vorlage schon mal in der Suchform von "post" auf 
"get" geändert aber das kann es ja nicht sein. Es kann, wie mir gerade 
einfällt ja auch nicht an web2pdf liegen, es muss ja in der Indizierung 
liegen, da die Links so aussehen:

http://st-josef-calw.de/index.php?id=45&tx_news_pi1[day]=1&tx_news_pi1[month]=8&tx_news_pi1[news]=3&tx_news_pi1[year]=2015*&tx_web2pdf_pi1[action]=&tx_web2pdf_pi1[argument]=printPage&tx_web2pdf_pi1[controller]=Pdf&cHash=25594bd64db52934e968d06ecab07c3c*

Haben Sie eine Idee, wie die Parameter "*tx_web2pdf_pi1*" in den Link 
kommen?




Mit einem freundlichen Gruß aus Jülich

Kurt Kunig

*kupix web-design*
Sternschanze 16
52428 Jülich

Tel.    : 02461 / 910 111
Fax.    : 02461 / 910 112
Mobil   : 0173 / 252 0001
Email   : gf@kupix.de
Internet: http://www.kupix.de

Geschäftsführung: Kurt Kunig, Sitz des Unternehmens: Jülich, Kreis Düren 
- Ust-ID: DE256894227

*WICHTIGER HINWEIS:* Diese E-mail, die angehängten Dateien und deren 
Inhalt sind ausschließlich für den oder die oben bezeichneten Adressaten 
bestimmt und können vertraulicher Natur sein und/oder Geschäfts- oder 
Betriebsgeheimnisse enthalten. Jeder Zugriff sowie jegliche Nutzung, 
Verbreitung oder Speicherung durch andere Personen ist nicht gestattet. 
Eine Zuwiderhandlung kann strafrechtlich verfolgt werden. Sollten Sie 
diese E-mail irrtümlich erhalten haben, bitten wir Sie, den Absender 
umgehend zu benachrichtigen und anschließend die E-mail zu löschen. Wir 
danken für Ihre Kooperation.

*Important information:* This message and attachment(s) are intended 
solely for use by the addressee and may contain information that is 
privileged, confidential or otherwise exempt from disclosure under 
applicable law. If you are not the intended recipient or agent thereof 
responsible for delivering this message to the intended recipient, you 
are hereby notified that any dissemination, distribution or copying of 
this communication is strictly prohibited. If you have received this 
communication in error, please notify the sender immediately by 
telephone and with a 'reply' message. Thank you for your co-operation.
