### ISSUE TITLE
pdfStyleSheet = print doens't work

### ISSUE THREAD

**Issue by ghost** [mittwald/typo3-web2pdf#70]
Hi
I added plugin.tx_web2pdf.settings.pdfStyleSheet = print in typoscript but hidden areas in the print.css file are always present on the pdf file.
TYPO3 7.6.18
web2pdf 1.1.16

Thanks for your help !

**Comment by pstranghoener** [comment]
Please check it with new version of web2pdf.

**Comment by Skdot** [comment]
Hey,
I have the same Problem. The stylesheets won't load

**Typo3** 8.7.12
**web2pdf** 1.2.1

Thank you

**Comment by pstranghoener** [comment]
Already fixed.
