### ISSUE TITLE
PHP 7.1 leads to an uncaught TYPO3 Exception in mpdf when rendering the PDF

### ISSUE THREAD

**Issue by bernhardberger** [mittwald/typo3-web2pdf#76]
#1476107295: PHP Warning: A non-numeric value encountered in /html/surf/releases/20170720153122/htdocs/typo3conf/ext/web2pdf/Vendor/mpdf/mpdf/mpdf.php line 30648

**Comment by kpurrmann** [comment]
#74 Waiting for merge
