### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by tbeaurin** [mittwald/typo3-web2pdf#77]
Hello,
I have some problem, the image are not found in the PDF. (tried with png and jpg)
The path is correct if i want to see my page in HTML.

Thnaks to you !

**Comment by kpurrmann** [comment]
@tbeaurin Could you please provide your php and TYPO3 version? We could not reproduce this error with png and jpg files.

**Comment by FrankAlbrecht** [comment]
Hello, we have the same problem. Our TYPO3 Version is 8.7.4 and the PHP Version is 7.0.2. We have no images in the generated PDF.

**Comment by pstranghoener** [comment]
@FrankAlbrecht Which Version of the Extension are you using ?  And also a link to it what be great.

**Comment by FrankAlbrecht** [comment]
Hi, our version of the extension is 1.2.1. I'm sorry but i can not give you a link. I am also using the bootstrap package from benjamin kott.

**Comment by pstranghoener** [comment]
Sorry, but than we can not help. 

Best Regards Philipp
