### ISSUE TITLE
Problem loading versioned CSS-files

### ISSUE THREAD

**Issue by mgante** [mittwald/typo3-web2pdf#79]
We have some problems here styling the document.

In the mpdf-Library the CSS-files could not be found while it tries to load the files from the local filesystem. Maybe, we found two problems there:

1) The local path that has been generated from web-path contains a double-slash. Maybe a simple check/replacement can fix this.

2) In the path, the version-number still remains (/path/to/file/styles.19384637.css for example), so it can't be found since this is added by the CMS. Here a preg_replace could possibly help, although there might be CSS-files with numbers in it.

We use:
TYPO3 7.6.20
PHP 7.0.9-pl0
web2pdf 1.1.6

All is located in mPDF::_get_file($path) (mpdf.php, line 14193).
But maybe one could implement a workaround in the extension itself.

**Comment by kpurrmann** [comment]
@mgante Both issues are related to mpdf lib. We won't fix them here.
