### ISSUE TITLE
jede Menge Warnings von mpdf

### ISSUE THREAD

**Issue by kurtwithslc** [mittwald/typo3-web2pdf#81]
Hallo,
ich habe web2pdf im Einsatz in Typo3 8.7.6
 
Allerdings wird das Protokoll mit einer Unmenge von Warnings zugemüllt (auch ohne dass ein PDF erstellt wird!). Wenn ich die WEB site einmal komplett abrufe habe ich über 500 derartige Warnings im Protokoll.
Beispiele:
Core: Error handler (FE): PHP Warning: A non-numeric value encountered in /html/typo3/typo3conf/ext/web2pdf/Vendor/mpdf/mpdf/mpdf.php line 6387
oder line 2003, line 2006, line 1889

Core: Error handler (FE): PHP Warning: Division by zero in /html/typo3/typo3conf/ext/web2pdf/Vendor/mpdf/mpdf/mpdf.php line 7096
oder line 7095,  line 7094,  line 7093, line 3337, line 3335

jemand eine Idee?

LG Kurt

**Comment by abeyl** [comment]
Kann mit den Anpassungen aus https://github.com/mittwald/typo3-web2pdf/pull/82 behoben werden.

**Comment by pstranghoener** [comment]
We published a new Version (1.2.0) in TER that fixes the problem.
