### ISSUE TITLE
"Could not scan for classes inside " after update to 1.2.0

### ISSUE THREAD

**Issue by kurtwithslc** [mittwald/typo3-web2pdf#85]
After updating to version 1.2 Extension manager shows:
Oops, an error occurred!
Could not scan for classes inside "/home/www/pxxxxxxx/html/typo3/typo3conf/ext/web2pdf/Vendor/mpdf/mpdf" which does not appear to be a file nor a folder

Output is broken in FrontEnd

**Comment by kpurrmann** [comment]
Will officially fix that on monday. May you delete the ext_autoload.php. That Is the only place where deprecated vendor path Is defined.

**Comment by kurtwithslc** [comment]
Great!

liebe Grüsse
Kurt Knote

Mühlweg 39
D-92637 Weiden
kurt.knote@t-online.de

**Comment by kurtwithslc** [comment]
ok,
after deleting this file there is still no frontend output, but an error is thrown:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Invalid size representation "a3" | Mpdf\MpdfException thrown in file phar:///html/typo3/typo3conf/ext/web2pdf/Libraries/mpdf.phar/vendor/mpdf/mpdf/src/SizeConverter.php in line 35. Requested URL: ...


PS: Size setting is: A4, Landscape

Liebe Grüsse
Kurt Knote

Mühlweg 39
D-92637 Weiden
kurt.knote@t-online.de

**Comment by kan0ne** [comment]
Hello everybody,
i had the same problem after updating to version 1.2. So i deleted the ext_autoload.php file.

But now when i click the link in FE i get 
Could not analyse class: "Mpdf\Mpdf" maybe not loaded or no autoloader? Class Mpdf\Mpdf does not exist

greetings martin

**Comment by pstranghoener** [comment]
We published a new Version (1.2.1) in TER that fixes the problem.
