### ISSUE TITLE
PDFs on ISAPI/IIS/FCGI/FPM configured Webserver will not determine the correct url protocol

### ISSUE THREAD

**Issue by Qixuga** [mittwald/typo3-web2pdf#88]
PDFs on ISAPI/IIS/FCGI/FPM got wrong url-protocol - https instead of http.
The reason ist the following function:

typo3conf/ext/web2pdf/Vendor/mpdf/mpdf/mpdf.php

```
function SetBasePath($str='') {
...
// if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']) { // got wrong https on upper listen http-serverconfigs, have to be be:
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] && ($_SERVER['HTTPS'] != 'off') ) {
...
}

```

Tested with actual module and works fine :-)

More informations look at php manual:
http://php.net/manual/en/reserved.variables.server.php#HTTPS

Thank you!

**Comment by pstranghoener** [comment]
Thanks for the report, but its a bug in the libary of mpdf we use. Its a known bug in mpdf https://github.com/mpdf/mpdf/issues 

Please report it to the guys from mpdf. 

Best Regards Philipp

**Comment by Qixuga** [comment]
Thank you, already listen there:
[Method SetBasePath has incorrect condition to check whether is server HTTPS or not #297](https://github.com/mpdf/mpdf/issues/297)
