### ISSUE TITLE
Cannot find TTF TrueType font file "DejaVuSansMono.ttf" in configured font directories. 

### ISSUE THREAD

**Issue by MarkusBausK** [mittwald/typo3-web2pdf#89]
Hi,

I try to use the extension but it is not working by typoscript. I try to get the link for generating pdf by using <f:cObject typoscriptObjectPath="lib.web2pdf" /> in my fluid template. After clicking I get an extbase error message "Cannot find TTF TrueType font file "DejaVuSansMono.ttf" in configured font directories. "

By plugin it seems to work but I need the link in the template.

EDIT: The error happens on tx_news detailpage!

**Comment by jeemit2007** [comment]
Hi Markus

today , I have faced this error on web2pdf extension.

I have added the DejaVuSansMono.ttf on following folder : /typo3conf/ext/web2pdf/Resources/Public/Fonts/

that resolved my problem , now I can download the pdf now and no error message anymore. Extension works fine.

We can download the file from this github repository : https://github.com/hbin/top-programming-fonts

thanks
Best Regards,
Jimit Shah

**Comment by pstranghoener** [comment]
We  fixed in v1.2.4 and v2.0.0

**Comment by IsikAkgun** [comment]
I'm using Typo3v10 and web2pdf v2.0.1 and I also got the _"Cannot find TTF TrueType font file "DejaVuSansMono.ttf" in configured font directories."_ message.
There is also no **DejaVuSansMono.ttf** in **\typo3conf\ext\web2pdf\Resources\Public\Fonts**
