### ISSUE TITLE
Custom pdf title

### ISSUE THREAD

**Issue by rareshluk** [mittwald/typo3-web2pdf#9]
Is it possible to give the pdf the "custom" page title of the page, instead of the actual page:title?

For example, on a single view page of tt_news, called News details in the backend, I would like the pdf name to be "News title.pdf" instead of "News details.pdf"

Thanks,
Luca

**Comment by rareshluk** [comment]
For example, having a dynamic news title on the single news page:

temp.newsTitle = RECORDS
temp.newsTitle {
  dontCheckPid = 1
        tables = tx_news_domain_model_news
        source.data = GP:tx_news_pi1|news
        source.intval = 1
        conf.tx_news_domain_model_news = TEXT
        conf.tx_news_domain_model_news {
            field = title
            htmlSpecialChars = 1
        }
        stdWrap.noTrimWrap = |<title> | - WebsiteName</title>|
}

page.headerData.1 >
page.headerData.1 < temp.newsTitle

Would it possible that the pdf takes the title that the script above generates for each news record?

**Comment by kpurrmann** [comment]
The correct way would be to configure the detail page , that the title of the news is displayed in title-tag.

**Comment by rareshluk** [comment]
It is displaying in the title tag.
But the name of the pdf to download stay the same for all the news

**Comment by kpurrmann** [comment]
You're right. Improved in 217b50b. New version will be soon available.

**Comment by rareshluk** [comment]
Perfect!
Thanks!
Looking forward to it!

**Comment by rareshluk** [comment]
Hi,

Is this feature added in the 1.1 version?

Thanks

**Comment by martin-helmich** [comment]
@rareshluk, yes, this feature is included in the v1.1.0 version.

**Comment by rareshluk** [comment]
I have a page title generated via Typoscript and this doesn't get shown in
the PDF title. It still shows the backend page title.
Tested on v1.1 on TYPO3 ver. 6.2.
