### ISSUE TITLE
Fonts are not being applied

### ISSUE THREAD

**Issue by taniamorales** [mittwald/typo3-web2pdf#91]
Version 1.2.1 from TER, TYPO3 8.7
I compared with 
http://typo3.p424591.webspaceconfig.de/index.php?id=55
The font is not applied on the generated PDF so you must be aware of the issue.

This problem was intended to be fixed on the Pull request: https://github.com/mittwald/typo3-web2pdf/pull/65/commits/e378257c069e57b461003a0a1966058a355c1940

I have tried Andriy solution but it does not work.

Could you give us any feedback about the status of this issue please. Is there is a way to configure the mPdf class to add the new font, the changes suggested by Andriy seem to be a good way to go but the class is not adding the new font.

**Comment by pstranghoener** [comment]
We fixed that in v1.2.4 and v2.0.0 

If you want to add new fonts add them under Resources/Public/Fonts
