### ISSUE TITLE
Invalid size representation "a3",  Version 1.2.1, TYPO3 8.7.16, Php 7.1

### ISSUE THREAD

**Issue by taunusweb** [mittwald/typo3-web2pdf#92]
Hi,
I get this Error: 
`Mpdf\MpdfException thrown in file
phar:///html/typo3/typo3conf/ext/web2pdf/Libraries/mpdf.phar/vendor/mpdf/mpdf/src/SizeConverter.php in line 35.`
Maybe it is the same Problem like in #85? I'm using the Plugin on a Page and I get the Error, when I click on "Print current Page".

Thanks
Uli

**Comment by pstranghoener** [comment]
Bug already fixed.
