### ISSUE TITLE
Composer installation of 1.2.x not possible

### ISSUE THREAD

**Issue by chriwo** [mittwald/typo3-web2pdf#94]
The composer require command "composer require mittwald/web2pdf" install version 1.1.2. An update to version 1.2.x follows this error message

> The requested package mittwald/web2pdf ^1.2 exists as mittwald/web2pdf[1.1.2] but these are rejected by your constraint.

I think that's 2 mistakes. First in composer.json and ext_emconf.php, the version ist defined as 1.1-dev. The second is dev-master alias shows to branch "1.0.x-dev" which not exists.

**Comment by pstranghoener** [comment]
Fixed in Version 1.2.2
