### ISSUE TITLE
fcgi:error / 500 after 8.7.17 Core Update - TYPO3-CORE-SA-2018-002

### ISSUE THREAD

**Issue by hhchrizzo** [mittwald/typo3-web2pdf#95]
My website ends up in 500 Internal Server Errors after upgrading from TYPO3 8.7.16 to TYPO3 8.7.17
Hours later i figured out that there went something wrong with the web2pdf Exenstion. If i disable the Extension the CMS works as well.

I think the problems comes with [TYPO3-CORE-SA-2018-002](https://typo3.org/security/advisory/typo3-core-sa-2018-002/) and the usage of .phar files.
If i move or delete typo3conf/ext/web2pdf/Libraries/mpdf.phar the Backend works again.
If i set the phars accessrights e.g. to '110' the Backend works too but with the Warning:
`
PHP Warning
Core: Error handler (BE): PHP Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/xxx/typo3conf/ext/web2pdf/Libraries/mpdf.phar/vendor/autoload.php) is not within the allowed path(s): (/var/www/vhosts/xxx/:/tmp/) i`

TYPO3 Version: 8.7.17
Webserver: Apache
PHP Version: 7.1.19
Database (Default): MySQL 5.5.56
Application Context: Production
Composer mode: Enabled
Operating System : Linux 3.10.0-693.17.1.el7.x86_64

**Comment by hhchrizzo** [comment]
Maybe related to: https://forge.typo3.org/issues/85547

**Comment by pstranghoener** [comment]
Is fixed with TYPO3 Version 8.7.18
