### ISSUE TITLE
PHP-Basedir-Error

### ISSUE THREAD

**Issue by jacques2017** [mittwald/typo3-web2pdf#98]
Hello,
I get the following error, when I try to print a page as PDF:

Uncaught TYPO3 Exception
#1476107295: PHP Warning: is_file(): open_basedir restriction in effect. File(/) is not within the allowed path(s): ([... path deleted]) in phar:///var/www/[...]/typo3conf/ext/web2pdf/Libraries/mpdf.phar/vendor/composer/../mpdf/mpdf/src/Mpdf.php line 13168 (More information)

To change the basedir is not an option. Is this a bug or where can I change the path of the file?

Please help.
Thanks,
Jacques

**Comment by SicorDev** [comment]
We have the same problem. Last good one is 1.1.6, that was the last before the phar got introduced.
Disabling Open Base Dir does fix the problem in theory, but is certainly not an option on a live server.

**Comment by wwenzel** [comment]
Is there any solution or workaround (except disabling open basedir) available for this problem?

**Comment by pstranghoener** [comment]
We fixed that in v1.2.4 and v2.0.0
