### ISSUE TITLE
composer can't find 1.2.2

### ISSUE THREAD

**Issue by nbiwki** [mittwald/typo3-web2pdf#99]
Hello,

i try to load this extension with composer, but it won't get install 1.2.2

from composer.json:
`{ "type": "git", "url": "https://github.com/mittwald/typo3-web2pdf" } `
in repository

then i try "composer require mittwald/web2pdf:1.2.2" and get follow message:

`The requested package mittwald/web2pdf 1.2.2 exists as mittwald/web2pdf[1.1.2, 0.0.2, 0.0.3, 0.0.4, 1.0.1, 1.0.2, 1.0.5, 1.1.0, 1.1.1, 1.1.3, 1.1.4] but these are rejected by your constraint.`

And "composer why-not mittwald/web2pdf:1.2.2" show me that 1.2.2 not exists:

`There is no installed package depending on "mittwald/web2pdf" in versions not matching 1.2.2`

best regards

**Comment by pstranghoener** [comment]
The Extension was not avaiable on packagist and now it is:  https://packagist.org/packages/mittwald/web2pdf 

So it should work now
